version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      major-updates:
        update-types:
          - major
      minor-updates:
        update-types:
          - minor
      patch-updates:
        update-types:
          - minor