version: '3.8'

services:
  database:
    image: neo4j:5.1.0
    container_name: database
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/neo4j}  # Add default value
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_logs_debug_level=INFO
      - NEO4J_dbms_logs_query_enabled=OFF
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/import
      - neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD:-neo4j}", "RETURN 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - multiforum-network

  backend:
    image: cluse/multiforum-backend:latest
    container_name: multiforum-backend
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - CYPRESS_ADMIN_TEST_EMAIL=${CYPRESS_ADMIN_TEST_EMAIL}
      - CYPRESS_ADMIN_TEST_USERNAME=${CYPRESS_ADMIN_TEST_USERNAME}
      - ENVIRONMENT=local
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_CREDENTIALS_BASE64=${GOOGLE_CREDENTIALS_BASE64}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-neo4j}
      - NEO4J_URI=bolt://database:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - SERVER_CONFIG_NAME=${VITE_SERVER_NAME:-Gennit}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - multiforum-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multiforum-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - GRAPHQL_URL_FOR_TYPES=${GRAPHQL_URL_FOR_TYPES:-http://localhost:4000}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
      - VITE_AUTH0_CALLBACK_URL=${VITE_AUTH0_CALLBACK_URL:-http://localhost:3000}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_CLIENT_SECRET=${VITE_AUTH0_CLIENT_SECRET}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_PASSWORD=${VITE_AUTH0_PASSWORD}
      - VITE_AUTH0_PASSWORD_2=${VITE_AUTH0_PASSWORD_2}
      - VITE_AUTH0_SCOPE=${VITE_AUTH0_SCOPE}
      - VITE_AUTH0_URL=${VITE_AUTH0_URL}
      - VITE_AUTH0_USERNAME=${VITE_AUTH0_USERNAME}
      - VITE_AUTH0_USERNAME_2=${VITE_AUTH0_USERNAME_2}
      - VITE_BASE_URL=${VITE_BASE_URL:-http://localhost:3000}
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-development}
      - VITE_GOOGLE_CLOUD_STORAGE_BUCKET=${VITE_GOOGLE_CLOUD_STORAGE_BUCKET}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_GRAPHQL_URL=${VITE_GRAPHQL_URL:-http://localhost:4000}
      - VITE_LIGHTGALLERY_LICENSE_KEY=${VITE_LIGHTGALLERY_LICENSE_KEY}
      - VITE_LOGOUT_URL=${VITE_LOGOUT_URL:-http://localhost:3000}
      - VITE_OPEN_CAGE_API_KEY=${VITE_OPEN_CAGE_API_KEY}
      - VITE_OPEN_GRAPH_API_KEY=${VITE_OPEN_GRAPH_API_KEY}
      - VITE_SERVER_NAME=${VITE_SERVER_NAME:-Gennit}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - multiforum-network

networks:
  multiforum-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins: